//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPata
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosLogin
    {
        public int Id { get; set; }
        public string Property1 { get; set; }
        public System.DateTime dataLogin { get; set; }
        public System.DateTime dataExpirar { get; set; }
        public int idConta { get; set; }
    }
}
