//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Conta> ContaSet { get; set; }
        public DbSet<Terapeuta> TerapeutaSet { get; set; }
        public DbSet<Paciente> PacienteSet { get; set; }
        public DbSet<EpisodioClinico> EpisodioClinicoSet { get; set; }
        public DbSet<DadosLogin> DadosLoginSet { get; set; }
    }
}
