//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sintoma
    {
        public Sintoma()
        {
            this.EpisodioClinico = new HashSet<EpisodioClinico>();
        }
    
        public int Id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<EpisodioClinico> EpisodioClinico { get; set; }
    }
}
