//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nome { get; set; }
        public string token { get; set; }
        public string cc { get; set; }
    }
}
